# Generated by Django 5.0.3 on 2024-05-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.CharField(max_length=300)),
                ('priority_level', models.CharField(max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
