# Generated by Django 5.0.3 on 2024-05-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baby_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='received_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
