# Generated by Django 5.0.3 on 2024-05-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baby_app', '0004_alter_notification_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='received_at',
            field=models.DateTimeField(),
        ),
    ]
